### ISSUE TITLE
add taxon/with_phenotype

### ISSUE THREAD

**Issue by mjy** [phenoscape/phenoscaperb#4]

**Comment by sckott** [comment]
query that works:

```
???
```

**Comment by mjy** [comment]
http://kb.phenoscape.org/apidocs/#/Taxa/get_taxon_with_phenotype

```
curl -X GET "http://kb.phenoscape.org/api/taxon/with_phenotype?entity=%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001703%3E&quality=%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000052%3E&in_taxon=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FVTO_0037519&parts=true&historical_homologs=false&serial_homologs=false&limit=20&offset=0&total=false" -H  "accept: application/json"
```

**Comment by sckott** [comment]
@mjy can you get me an example that returns quickly for the doc examples and tests

**Comment by mjy** [comment]
@sckott This query uses most of the params, is limited to return one result.  Should be fast enough, especially if VCR used.

`curl -X GET "http://kb.phenoscape.org/api/taxon/with_phenotype?entity=%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0008897%3E&quality=%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000052%3E&in_taxon=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FVTO_0059975&parts=true&historical_homologs=false&serial_homologs=false&limit=1&offset=0&total=true" -H  "accept: application/json"`

**Comment by hlapp** [comment]
Wouldn't you want to leave off the `total=true` parameter, or is the count, not the taxon, what you're after?

**Comment by mjy** [comment]
Depends what is being tested.  If it just a test that "this API endpoint
works" then this request is optimized for speed.  If the test is for
functionality then we need many requests, potentially combinatoric per
params (hinting that there are maybe too many on this API end point).   I
do actually use count in Fishtank, but that's unrelated.

**Comment by hlapp** [comment]
I don't want to belabor this too much further, but just to be clear, a count query requires aggregation (unless counts are precomputed, which here they are not), and hence is _slower_, not faster, than not counting, even if sorting is involved (aggregation necessarily requires sorting, too).

**Comment by sckott** [comment]
thanks @mjy and @hlapp - will do both - using `vcr` for test caching, so at least in the test suite won't take any time after cached

**Comment by mjy** [comment]
You're right about query speed.

A minor counter (which might also hint at another issues with the endpoint,
it returns multiple "types" of responses).  The response we get on this
query is:
```

{
  "total": 1}
```

The VCR gem caches the response after the first run, so in the long
run a small response might be faster (parsing) for the test suite.

Regardless, the entity, quality, taxon is paired down to optimize a
minimal result, etc.  I think we don't need to worry more about speed
per se here, we're really nitpicking.
